services:
  # ---------------------------------------- Apps ----------------------------------------
  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    env_file:
      - ./apps/consumer/.env
    environment:
      NODE_ENV: development
      PYTHONUNBUFFERED: 1
    networks:
      - shared-network

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - consumer
      - server
    env_file:
      - ./apps/api/.env
    environment:
      NODE_ENV: development
      PYTHONUNBUFFERED: 1
    networks:
      - shared-network

  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./apps/server/.env
    environment:
      NODE_ENV: development
      PYTHONUNBUFFERED: 1
    networks:
      - shared-network

  web:
    build:
      context: ./apps/web
      dockerfile: ../../docker/web.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - consumer
      - server
    env_file:
      - ./apps/web/.env
    environment:
      NODE_ENV: development
    networks:
      - shared-network

  # ---------------------------------------- Packages ----------------------------------------
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.1
    ports:
      - 8080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'multi2vec-clip'
      CLIP_INFERENCE_API: http://multi2vec-clip:8080
      NODE_ENV: dev
    env_file:
      - .env
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8080/v1/.well-known/ready || exit 1" ]
      interval: 3s
      timeout: 10s
      retries: 5

  multi2vec-clip:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    environment:
      ENABLE_CUDA: 0
    restart: unless-stopped
    networks:
      - shared-network

  rabbitmq:
    build:
      context: ./packages/rabbitmq
      dockerfile: ../../docker/rmq.Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - shared-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 30s
      retries: 5

  ocr:
    build:
      context: ./packages/ocr
      dockerfile: ../../docker/ocr.Dockerfile
    ports:
      - "9000:9000"
    restart: always
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://127.0.0.1:9000/ || exit 1" ]
      interval: 2s
      timeout: 10s
      retries: 10

networks:
  shared-network:
    external: true

volumes:
  weaviate_data:
  rabbitmq-data:
