map = {
    "application/vnd.ms-excel": None,
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": None,
    "application/vnd.oasis.opendocument.spreadsheet": None,
    "application/vnd.sun.xml.calc": None,
    "application/vnd.stardivision.calc": None,
    "application/vnd.lotus-1-2-3": None,
    "application/vnd.google-apps.spreadsheet": None,
    "application/vnd.kde.kspread": None,
    "application/x-kspread": None,
    "application/x-starcalc": None,
    "application/x-dbf": None,
    "application/x-sylk": None,
    "text/csv": None,
    "text/tab-separated-values": None,
    "application/x-excel": None,
    "application/vnd.corel-quattro-pro": None,
}
