---
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'multi2vec-clip' # comma-separated list of modules to enable
      CLIP_INFERENCE_API: http://multi2vec-clip:8080 # Set the inference API endpoint
    env_file:
      - .env
    networks:
      - shared-network

  multi2vec-clip:
    # Set the name of the inference container
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    environment:
      ENABLE_CUDA: 0 # Set to 1 to enable GPU support
    ports:
      - "8081:8080" # Map the container's port 8080 to host port 8081
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  weaviate_data:
...
