[tool.poetry]
name = "weaviate-py"
version = "0.1.0"
description = ""
authors = ["Mark Shteyn <markshteyn1@gmail.com>"]
readme = "README.md"
packages = [{ include = "weaviate_utils" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
weaviate-client = "^4.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
