from app.processors.document.processor import *

map = {
    "text/plain": PlainTextExtractor(),
    "application/plain": PlainTextExtractor(),
    "application/msword": LegacyWordExtractor(),
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": WordExtractor(),
    "application/pdf": PDFExtractor(),
    "application/rtf": RTFExtractor(),
    "text/rtf": RTFExtractor(),
    "application/vnd.oasis.opendocument.text": ODTExtractor(),
    "application/vnd.oasis.opendocument.text-template": ODTExtractor(),
    "text/markdown": MarkdownExtractor(),
    "text/x-markdown": MarkdownExtractor(),
    "text/html": HTMLExtractor(),
    "application/html": HTMLExtractor(),
    "application/xhtml+xml": HTMLExtractor(),
    "text/xml": XMLExtractor(),
    "application/xml": XMLExtractor(),
    "application/json": JSONExtractor(),
    "application/vnd.apple.pages": ApplePagesExtractor(),
    "application/epub+zip": EPUBExtractor(),
    "text/x-tex": TeXExtractor(),
    "application/x-tex": TeXExtractor(),
    "application/x-latex": TeXExtractor(),
}
