from app.processors.document.document import *

map = {
    "text/plain": PlainTextExtractor(),
    "application/plain": PlainTextExtractor(),
    "application/msword": LegacyWordExtractor(),
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": WordExtractor(),
    "application/pdf": PDFExtractor(),
    "application/rtf": RTFExtractor(),
    "text/rtf": RTFExtractor(),
    "application/vnd.oasis.opendocument.text": ODTExtractor(),
    "application/vnd.oasis.opendocument.text-template": ODTExtractor(),
    "text/markdown": MarkdownExtractor(),
    "text/x-markdown": MarkdownExtractor(),
    "text/html": HTMLExtractor(),
    "application/html": HTMLExtractor(),
    "application/xhtml+xml": HTMLExtractor(),
    "text/xml": XMLExtractor(),
    "application/xml": XMLExtractor(),
    "application/json": None,
    "application/vnd.ms-works": None,
    "application/vnd.apple.pages": None,
    "application/epub+zip": None,
    "application/vnd.lotus-1-2-3": None,
    "text/x-tex" "application/x-tex": None,
    "application/x-latex": None,
    "application/x-troff-ms": None,
    "application/vnd.wap.xhtml+xml": None,
}
