version: "3.8"

services:
  rabbitmq:
    build:
      context: .
    ports:
      - "5672:5672"    # Messaging port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  rabbitmq-data:
