[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Mark Shteyn <markshteyn1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
pika = "^1.3.2"
google-api-python-client = "^2.154.0"
pytesseract = "^0.3.13"
pandas = "^2.2.3"
pillow = "^11.0.0"
pypdf2 = "^3.0.1"
docx = "^0.2.4"
mammoth = "^1.8.0"
fitz = "^0.0.1.dev2"
striprtf = "^0.0.28"
bs4 = "^0.0.2"
python-docx = "^1.1.2"
pymupdf = "^1.25.0"
odf = "^0.0.1"
odfpy = "^1.4.1"
weaviate = "^0.1.2"
python-dotenv = "^1.0.1"
easyocr = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
